In [2]:

import numpy as np

In [170]:
#Task 1... 1D ARRAY
array = np.arange(0,10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [171]:
#Task 2...3*3 Boolean Value True
array = np.ones((3,3), dtype=bool)
print(array)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [172]:
#Task 3...ODD Number
odd_number = []
array = np.arange(0,9)
for i in array:
    if (i % 2) != 0:
        odd_number.append(i)
    else:
        None
print(odd_number)
 


[1, 3, 5, 7]


In [173]:
#Task 4...repalce Odd Number with -1
array = np.arange(0,11)
print(array)
array[array % 2 != 0] = -1
print(array)


[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]


In [174]:
#Task 5...1D array to 2D array
array = np.arange(0,10)
new_array = np.reshape(array, (2,5))
print(new_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [175]:
#Task 6...stack two array vertically and calculate total 
a = np.arange(0,9).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
result = np.vstack((a,b))
print(result)
total = np.sum(result)
print(total)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
162


In [3]:
#Two Array. Remove all repeating items present in second array 
a = np.array([1,2,3,4,5])
b = np.array([ 4,5,6,7,8,9])

print(a)
res_array = np.setdiff1d(b, a)
print(res_array)

[1 2 3 4 5]
[6 7 8 9]
